spring:
  application:
    name: wo

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##DESARROLLO
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: mail@gmail.com
    password: asseoezlmxriydfllqsa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8002


